name: PR merge development and sandbox tags
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: force sandbox tag
        run: |
          git tag -f sandbox
          git push -f origin sandbox