name: Webhooks Test

on:
  repository_dispatch:
    types: [webhook-trigger]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Log Vars
        run: echo 'Running...'
      - name: Log Release
        run: echo ${{ github.event.client_payload.release }}
      - name: Log Ref
        run: echo ${{ github.ref_name }}
