name: Webhooks Test

on:
  repository_dispatch:
    types: [webhook-trigger]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Log Vars
        run: echo 'Running...'
      - name: Log Vars
        run: echo ${{ github.event.client_payload.release }}
