name: Webhooks Test

on:
  repository_dispatch:
    types: [webhook-trigger]

jobs:
  get-release-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set env
        run: echo "FOO=$(git describe --tags --match "v*" --abbrev=0)" >> $GITHUB_ENV
      - name: Test
        run: echo ${{ env.FOO }}

      - name: Always
        run: echo "ALWAYS=$(git describe --tags --match "v*" --abbrev=0 --always)" >> $GITHUB_ENV
      - name: Test
        run: echo ${{ env.ALWAYS }}

      - name: Three
        run: echo "THREE=$(git describe --match "v[0-9]*.[0-9]*.[0-9]*" --abbrev=0 --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV
      - name: Test
        run: echo ${{ env.THREE }}
      
      - name: Four
        run: echo "FOUR=$(git describe --tags --match='v[0-9]*.[0-9]*.[0-9]*')" >> $GITHUB_ENV
      - name: Test
        run: echo ${{ env.FOUR }}
      
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Log Tag From Release
        run: echo ${{ steps.get-release-tag.outputs.tag }}
      - name: Log Release
        run: echo ${{ github.event.client_payload.release }}
      - name: Log Ref
        run: echo ${{ github.ref }}
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 15.0.0 # Optional fallback tag to use when no tag can be found
      - name: 'Log Tag'
        run: echo ${{ steps.previoustag.outputs.tag }}
  analyze-tags:
    runs-on: ubuntu-latest
    outputs:
      previous-tag: ${{ steps.previoustag.outputs.tag }}
      timestamp-diff: ${{ steps.diff.outputs.timestamp-diff }}
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --tags origin

      - name: git 1
        run: git describe --match "v[0-9]*.[0-9]*.[0-9]*" --abbrev=0 --tags $(git rev-list --tags --max-count=1)

      - name: git 2
        run: git describe --tags --match='v[0-9]*.[0-9]*.[0-9]*'

      - name: Get previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Get seconds from previous tag to now
        id: diff
        shell: bash
        env:
          TIMESTAMP_TAG: ${{ steps.previoustag.outputs.timestamp }}
        run: |
          echo "::set-output name=timestamp-diff::$(expr $(printf '%(%s)T') - $TIMESTAMP_TAG)"