name: Webhooks Test

on:
  repository_dispatch:
    types: [webhook-trigger]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Log Vars
        run: echo 'Running...'
      - name: Log Release
        run: echo ${{ github.event.client_payload.release }}
      - name: Log Ref
        run: echo ${{ github.ref }}
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 15.0.0 # Optional fallback tag to use when no tag can be found
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: 'Log patch'
        run: echo ${{ steps.semvers.outputs.patch }}
      - name: 'Log Tag'
        run: echo ${{ steps.previoustag.outputs.tag }}